check for existing function

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,9 +41,9 @@ jobs:
             export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
             export AWS_DEFAULT_REGION=${AWS_REGION}
             export FUNCTION_NAME=cci-demo
-            result=`aws lambda create-function --function-name ${FUNCTION_NAME} --runtime python3.6 --role ${AWS_ROLE_ARN}  --handler main --zip-file fileb://output/bundle.zip 2>&1 || echo "Creation Error"`
+            result=`aws lambda create-function --function-name ${FUNCTION_NAME} --runtime python3.6 --role ${AWS_ROLE_ARN}  --handler main --zip-file fileb://output/bundle.zip 2>&1 || echo "Unable to Create Function"`
             echo $result
-            if [[ "$result" == *Function already exist* ]]; then
+            if [[ "$result" == *"Function already exists"* ]]; then
               echo "Function exists, attempting update to LATEST"
               aws lambda update-function-code --function-name ${FUNCTION_NAME} --zip-file fileb://output/bundle.zip --publish            
             fi
