check for existing function

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,11 +37,16 @@ jobs:
       - run:
           name: Publish Lambda
           command: |
-            export AWS_ACCESS_KEY_ID=${AWS_KEY_ID}
-            export AWS_SECRET_ACCESS_KEY=${AWS_KEY_SECRET}
+            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
             export AWS_DEFAULT_REGION=${AWS_REGION}
-            aws lambda create-function --function-name cci-demo --runtime python3.6 --role ${AWS_USER_ARN}  --handler main --zip-file fileb://output/bundle.zip
-            #aws lambda update-function-code--function-name <<existing name>> --zip-file <<path to zip>> --publish
+            export FUNCTION_NAME=cci-demo
+            result=`aws lambda create-function --function-name ${FUNCTION_NAME} --runtime python3.6 --role ${AWS_ROLE_ARN}  --handler main --zip-file fileb://output/bundle.zip 2>&1 || echo "Creation Error"`
+            echo $result
+            if [[ "$result" == *Function already exist* ]]; then
+              echo "Function exists, attempting update to LATEST"
+              aws lambda update-function-code --function-name ${FUNCTION_NAME} --zip-file fileb://output/bundle.zip --publish            
+            fi
 
 workflows:
   version: 2
